site_name: Work Orders
pages:
- Home: index.md
- Motor Room: 
    - Round: MotorRoom-Round.md
    - Weekly: MotorRoom-Weekly.md
    - Monthly: MotorRoom-Monthly.md
    - Quarterly: MotorRoom-Quarterly.md
    - Annual: MotorRoom-Annual.md
    - Trienniel: MotorRoom-Triennial.md
- Daily Chemical Analysis:
    - Hardness Test: HardnessTest.md 
    - Total Alkalinity Test: Alkalinity.md
    - pH Test: phTest.md
    - Fluoride Analysis: FluorideAnalysis.md
    - Phosphorous Test: Phosphorous.md 
    - UV Test: UVTest.md     
- Calibration of the Turbidimeters: 
    - Online Turbidimeter 1720E Calibration and Cleaning Procedures (PART 1): 1720Part1.md 
    - Calibrating Hach 1720D Turbidimeter: 1720D.md 
    - Cleaning & Calibrating Hach 1720C: 1720_C_Cleaning.md
    - Cleaning & Calibrating Hach 1720D: 1720_D_Cleaning.md
    - Cleaning & Calibrating Hach 1720E: 1720_E_Cleaning.md
- Miscellaneous: 
    - Hourly Rounds:  HourlyRounds.md
    - SWAN Chlorine Analyzer Calibration: SwanCalibration.md
    - Changing & Calibrating Chlorine Analyzer: Cl2Calibration.md 
    - How to Calibrate The Chlorine Analyzer (CL 17): CL17_Calibration.md 
    - Back Washing Filters, "Manual Control": Backwash.md
    - Chlorine Residual Testing w/ DR5000: DR5000_ResidualTest.md
    - Total Chlorine: TotalChlorine.md 
    - Copper Test: CopperTest.md
    - Detergent Test: DetergentTest.md
    - Phenol's Test: PhenolTest.md  
    - Untitled: Untitled.md 
- Etse's Videos: 
    - Fluoride Test (Etse): FluorideTestEtse.md 
    - Chlorine Analysis with DR5000 (Etse): ChlorineTestEtse.md 
    - Autoclave Use (Etse): AutoclaveEtse.md 
    - Procedure for making Agar: AgarEtse.md 
    - HACH DR5000 UV, Calibration Test for Tap Water (ETSE): DR5000_Etse.md 
    - 2100 AN Turbidimeter Calibration (Etse): 2100Etse.md
    - Balance Calibration Check (Etse): BalanceEtse.md 
    - Online Turbidimeter 1720E Calibration (ETSE): 1720Etse.md 
    - Phosphorous Test, Tap Water (Etse): PhosphorousTapEtse.md 
    - Total Alkalinity Test Performance (Etse): TotalAlkalinityEtse.md 
    - Total Hardness Test Performance (Etse): TotalHardnessEtse.md 
    - Turbidimeter 1720C Calibration (Etse): 1720CCalibrationEtse.md 
    - Use of Quanti-Tray Sealer (Etse): QuantiTrayEtse.md 
    - Chlorine Analyzer Calibration (Etse): ChlorineCalibrationEtse.md
- Operations: 
    - End of the Month Numbers: EndOfMonth_Numbers.md 
    - High Service Pumping and Distrubution Operations (General): HS_PumpDistro_Operations.md
theme: readthedocs
markdown_extensions:
  - admonition:
